name: fire_base_project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  bloc: ^8.1.2
  cloud_firestore: ^4.14.0
  dartz: ^0.10.1
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  get: ^4.6.6
  get_it: ^7.6.6
  injectable: ^1.5.3
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  injectable_generator: ^1.5.3

flutter:
  uses-material-design: true
